### ISSUE TITLE
Dockerhub latest image not including Sample Verso Submodule

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_profile_editor#118]
Getting an error when trying to run the latest Dockerhub profile_editor image. 

```Error: ENOENT: no such file or directory, scandir '/opt/sinopia_profile_editor/sample_data_from_verso/data/profiles'
    at Object.readdirSync (fs.js:764:3)
    at loadProfiles (/opt/sinopia_profile_editor/source/versoSpoof.js:12:8)
    at Object.<anonymous> (/opt/sinopia_profile_editor/source/versoSpoof.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sinopia_profile_editor@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sinopia_profile_editor@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-29T16_43_08_690Z-debug.log```

**Comment by atz** [comment]
These lines do not persist between `build` and `register_image`:
https://github.com/LD4P/sinopia_profile_editor/blob/master/.circleci/config.yml#L45-L46

Thoughts:
- `npm run` seems like unnecessary indirection, no JS is involved or desired in the `git` call(s)
- need a persistence strategy for the populated submodules between "jobs": `persist_to_workspace` or cached
- Both those problems go away if the code is controlled in this repo directly and not via submodule

**Comment by atz** [comment]
Right now, we add 50MB to the container size just to get 2 MB of sample data.  That should be avoided.
